openid_connect.settings.ssofact:
  type: config_object
  label: 'OpenID Connect Newsfactory ssoFACT settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable client'
    settings:
      type: mapping
      mapping:
        client_id:
          type: string
          label: 'Client ID'
        client_secret:
          type: string
          label: 'Client secret'
        server_domain:
          type: string
          label: 'Server domain'
        scope:
          type: string
          label: 'Scope'
